import React from 'react'


export default function PrivacyPolicy() {

    return (
        <>
            <h3>Privacy Policy</h3>
            <p className="my-2">Privacy Policy</p>

            <p className="my-2">Effective date: july 26 2023</p>

            <p className="my-2">This Privacy Policy explains how we handle information provided or generated by users while using WebsiteToScreenshot.com (we, our, or us) and applies solely to information collected on www.websitetoscreenshot.com] (the Website). By accessing or using the Website, you agree to the practices described in this Privacy Policy.</p>

            <p className="my-2">Information We Collect</p>

            <p className="my-2">1.1. Personal Information: We do not directly collect any personal information such as names, addresses, email addresses, or phone numbers from users.</p>

            <p className="my-2">1.2. User-Provided Parameters: While using the Website, users may have the option to input parameters or data. We do not store or retain any user-provided parameters on our servers. The parameters are used solely for the purpose of generating the requested screenshot and are not associated with any personal information.</p>

            <p className="my-2">1.3. Cookies and Similar Technologies: We may use cookies and similar technologies to enhance user experience, enable certain functionalities, and gather anonymous usage statistics. These technologies do not collect any personally identifiable information.</p>

            <p className="my-2">Use of Information</p>

            <p className="my-2">2.1. Personal Information: Since we do not collect personal information, we do not use or disclose any such information.</p>

            <p className="my-2">2.2. User-Provided Parameters: The parameters provided by users are solely used to process and generate the requested screenshot. We do not share, store, or use these parameters beyond their immediate use for generating the screenshot.</p>

            <p className="my-2">2.3. Cookies and Similar Technologies: The information gathered through cookies and similar technologies is used for improving the functionality and performance of the Website. We do not link this information to any personally identifiable data.</p>

            <p className="my-2">Third-Party Services</p>

            <p className="my-2">3.1. The Website may use third-party services, such as web analytics tools or cloud service providers, to assist in the operation of the Website. These third-party services may collect non-personal information through cookies and similar technologies. We do not control the privacy practices of these third-party services and recommend reviewing their respective privacy policies.</p>

            <p className="my-2">Data Security</p>

            <p className="my-2">4.1. We implement reasonable technical and organizational measures to protect against unauthorized access, alteration, disclosure, or destruction of user-provided parameters and any non-personal information collected through cookies. However, please be aware that no data transmission over the internet or method of electronic storage is entirely secure.</p>

            <p className="my-2">Children Privacy</p>

            <p className="my-2">5.1. The Website is not intended for use by individuals under the age of 13. We do not knowingly collect any personal information from children under 13. If you believe we have inadvertently collected such information, please contact us immediately, and we will take appropriate steps to delete it.</p>

            <p className="my-2">Changes to this Privacy Policy</p>

            <p className="my-2">6.1. We reserve the right to update or modify this Privacy Policy at any time without prior notice. Any changes will be effective immediately upon posting on the Website. It is your responsibility to review this Privacy Policy periodically to stay informed about how we handle information.</p>

            <p className="my-2">Contact Us</p>

            <p className="my-2">7.1. If you have any questions, concerns, or requests regarding this Privacy Policy or our practices, please contact us at frederic.perr@gmail.com.</p>


        </>

    )
}
